"""Generate the notebooks/Performance_Analytics.ipynb notebook using nbformat."""
from __future__ import annotations

from pathlib import Path
import nbformat as nbf

notebook_path = Path(__file__).resolve().parents[1] / "notebooks" / "Performance_Analytics.ipynb"

nb = nbf.v4.new_notebook()

# Markdown and code cell contents
cells = [
    nbf.v4.new_markdown_cell(
        "# DAY 4 — Fund Performance Analytics\n\n"
        "This notebook computes risk and return metrics for all 40 schemes using the cleaned daily NAV history "
        "and benchmark index data. It implements the following calculations:\n"
        "1. Daily returns and distribution checks.\n"
        "2. CAGR for 1yr, 3yr, and 5yr (using max available history of 4.4 years as a proxy for 5yr).\n"
        "3. Sharpe Ratio (using Rf = 6.5% proxy, annualized).\n"
        "4. Sortino Ratio (using downside standard deviation for negative return days only).\n"
        "5. Alpha and Beta (using OLS regression vs Nifty 100 daily returns).\n"
        "6. Maximum Drawdown and worst drawdown date range.\n"
        "7. Fund Scorecard (weighted composite of ranks).\n"
        "8. Benchmark comparison chart and tracking error calculation.\n\n"
        "## Setup & Loading Data"
    ),
    nbf.v4.new_code_cell(
        "import sys\n"
        "from pathlib import Path\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import scipy.stats as stats\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n\n"
        "# Load data\n"
        "nav_df = pd.read_csv('../data/processed/clean_nav_history.csv')\n"
        "bench_df = pd.read_csv('../data/processed/clean_benchmark_indices.csv')\n"
        "master_df = pd.read_csv('../data/processed/clean_fund_master.csv')\n\n"
        "nav_df['date'] = pd.to_datetime(nav_df['date'])\n"
        "bench_df['date'] = pd.to_datetime(bench_df['date'])\n\n"
        "print(f\"Loaded {len(nav_df)} NAV rows, {len(bench_df)} benchmark rows, and {len(master_df)} funds.\")"
    ),
    nbf.v4.new_markdown_cell(
        "## 1. Compute Daily Returns & Validate Distributions\n\n"
        "We calculate `daily_return = nav_t / nav_t-1 - 1` for all 40 schemes."
    ),
    nbf.v4.new_code_cell(
        "nav_df = nav_df.sort_values(['amfi_code', 'date'])\n"
        "nav_df['daily_return'] = nav_df.groupby('amfi_code')['nav'].pct_change()\n\n"
        "# Compute summary statistics\n"
        "all_returns = nav_df['daily_return'].dropna()\n"
        "print(\"Daily Returns Distribution Statistics:\")\n"
        "print(f\"  Total return days: {len(all_returns)}\")\n"
        "print(f\"  Mean daily return: {all_returns.mean():.6%}\")\n"
        "print(f\"  Std Dev of daily returns: {all_returns.std():.6%}\")\n"
        "print(f\"  Min daily return: {all_returns.min():.6%}\")\n"
        "print(f\"  Max daily return: {all_returns.max():.6%}\")\n"
        "print(f\"  Skewness: {all_returns.skew():.4f}\")\n"
        "print(f\"  Kurtosis: {all_returns.kurtosis():.4f}\")\n\n"
        "# Plot distribution\n"
        "plt.figure(figsize=(10, 5))\n"
        "sns.histplot(all_returns, bins=100, kde=True, color='royalblue')\n"
        "plt.title(\"Distribution of Daily Returns Across All Schemes\", fontsize=12, fontweight='bold')\n"
        "plt.xlabel(\"Daily Return\")\n"
        "plt.ylabel(\"Frequency\")\n"
        "plt.show()"
    ),
    nbf.v4.new_markdown_cell(
        "## 2. Compute CAGR for 1yr, 3yr, 5yr\n\n"
        "We calculate CAGR: `CAGR = (NAV_end / NAV_start) ^ (1/n) - 1`.\n"
        "The NAV history runs from 2022-01-03 to 2026-05-29 (4.40 years). The 5-year CAGR is computed over this "
        "maximum available period."
    ),
    nbf.v4.new_code_cell(
        "end_date = pd.Timestamp(\"2026-05-29\")\n"
        "start_1yr = pd.Timestamp(\"2025-05-29\")\n"
        "start_3yr = pd.Timestamp(\"2023-05-29\")\n"
        "start_5yr = pd.Timestamp(\"2022-01-03\")\n\n"
        "cagr_records = []\n"
        "for code in nav_df['amfi_code'].unique():\n"
        "    fund_nav = nav_df[nav_df['amfi_code'] == code].set_index('date')\n"
        "    nav_end = fund_nav.loc[end_date, 'nav']\n"
        "    nav_1yr = fund_nav.loc[start_1yr, 'nav']\n"
        "    nav_3yr = fund_nav.loc[start_3yr, 'nav']\n"
        "    nav_5yr = fund_nav.loc[start_5yr, 'nav']\n"
        "    \n"
        "    cagr_1yr = (nav_end / nav_1yr) ** (1.0 / 1.0) - 1\n"
        "    cagr_3yr = (nav_end / nav_3yr) ** (1.0 / 3.0) - 1\n"
        "    \n"
        "    days_5yr = (end_date - start_5yr).days\n"
        "    years_5yr = days_5yr / 365.25\n"
        "    cagr_5yr = (nav_end / nav_5yr) ** (1.0 / years_5yr) - 1\n"
        "    \n"
        "    cagr_records.append({\n"
        "        'amfi_code': code,\n"
        "        'cagr_1yr_pct': cagr_1yr * 100,\n"
        "        'cagr_3yr_pct': cagr_3yr * 100,\n"
        "        'cagr_5yr_pct': cagr_5yr * 100\n"
        "    })\n\n"
        "cagr_df = pd.DataFrame(cagr_records)\n"
        "cagr_df.head()"
    ),
    nbf.v4.new_markdown_cell(
        "## 3. Sharpe and Sortino Ratios\n\n"
        "- Sharpe Ratio: `(Rp - Rf) / Std(Rp) * sqrt(252)` where `Rf = 6.5%`.\n"
        "- Sortino Ratio: same but denominator uses downside standard deviation (negative return days only)."
    ),
    nbf.v4.new_code_cell(
        "Rf_annual = 0.065\n"
        "Rf_daily = Rf_annual / 252\n\n"
        "ratio_records = []\n"
        "for code in nav_df['amfi_code'].unique():\n"
        "    fund_returns = nav_df[(nav_df['amfi_code'] == code) & (nav_df['daily_return'].notna())]['daily_return']\n"
        "    \n"
        "    excess = fund_returns - Rf_daily\n"
        "    sharpe = (excess.mean() / fund_returns.std()) * np.sqrt(252)\n"
        "    \n"
        "    downside_returns = fund_returns[fund_returns < 0]\n"
        "    sortino = (excess.mean() / downside_returns.std()) * np.sqrt(252)\n"
        "    \n"
        "    ratio_records.append({\n"
        "        'amfi_code': code,\n"
        "        'sharpe_ratio': sharpe,\n"
        "        'sortino_ratio': sortino,\n"
        "        'std_dev_ann_pct': fund_returns.std() * np.sqrt(252) * 100\n"
        "    })\n\n"
        "ratios_df = pd.DataFrame(ratio_records)\n"
        "ratios_df.head()"
    ),
    nbf.v4.new_markdown_cell(
        "## 4. Alpha and Beta\n\n"
        "We compute Alpha and Beta by running an OLS regression of daily returns against Nifty 100 returns.\n"
        "- `Beta = slope`\n"
        "- `Alpha = intercept * 252`"
    ),
    nbf.v4.new_code_cell(
        "bench_df = bench_df.sort_values(['index_name', 'date'])\n"
        "bench_df['daily_return'] = bench_df.groupby('index_name')['close_value'].pct_change()\n\n"
        "nifty100 = bench_df[(bench_df['index_name'] == 'NIFTY100') & (bench_df['daily_return'].notna())][['date', 'daily_return']]\n"
        "nifty100 = nifty100.rename(columns={'daily_return': 'bench_return'})\n\n"
        "alpha_beta_records = []\n"
        "for code in nav_df['amfi_code'].unique():\n"
        "    fund_ret = nav_df[(nav_df['amfi_code'] == code) & (nav_df['daily_return'].notna())][['date', 'daily_return']]\n"
        "    merged = pd.merge(fund_ret, nifty100, on='date', how='inner')\n"
        "    \n"
        "    slope, intercept, r_val, p_val, std_err = stats.linregress(merged['bench_return'], merged['daily_return'])\n"
        "    alpha_beta_records.append({\n"
        "        'amfi_code': code,\n"
        "        'alpha': intercept * 252 * 100,\n"
        "        'beta': slope\n"
        "    })\n\n"
        "alpha_beta_df = pd.DataFrame(alpha_beta_records)\n"
        "alpha_beta_df.head()"
    ),
    nbf.v4.new_markdown_cell(
        "## 5. Maximum Drawdown & Date Ranges\n\n"
        "Calculate `drawdown = NAV / running_max - 1` and find the worst peak-to-trough range."
    ),
    nbf.v4.new_code_cell(
        "dd_records = []\n"
        "for code in nav_df['amfi_code'].unique():\n"
        "    fund_nav = nav_df[nav_df['amfi_code'] == code].sort_values('date').reset_index(drop=True)\n"
        "    nav_series = fund_nav['nav']\n"
        "    date_series = fund_nav['date']\n"
        "    \n"
        "    running_max = nav_series.cummax()\n"
        "    drawdowns = nav_series / running_max - 1\n"
        "    max_dd = drawdowns.min()\n"
        "    \n"
        "    trough_idx = drawdowns.idxmin()\n"
        "    trough_date = date_series.iloc[trough_idx]\n"
        "    peak_val = running_max.iloc[trough_idx]\n"
        "    \n"
        "    peak_idx = nav_series.iloc[:trough_idx + 1][nav_series.iloc[:trough_idx + 1] == peak_val].index[-1]\n"
        "    peak_date = date_series.iloc[peak_idx]\n"
        "    \n"
        "    dd_records.append({\n"
        "        'amfi_code': code,\n"
        "        'max_drawdown_pct': max_dd * 100,\n"
        "        'drawdown_peak_date': peak_date.strftime('%Y-%m-%d'),\n"
        "        'drawdown_trough_date': trough_date.strftime('%Y-%m-%d')\n"
        "    })\n\n"
        "drawdown_df = pd.DataFrame(dd_records)\n"
        "drawdown_df.head()"
    ),
    nbf.v4.new_markdown_cell(
        "## 6. Fund Scorecard (0-100)\n\n"
        "We build a composite ranking using normalized percentile ranks:\n"
        "`Score = 30% * rank_3yr + 25% * rank_Sharpe + 20% * rank_Alpha + 15% * rank_expense (inverse) + 10% * rank_max_dd (inverse)`."
    ),
    nbf.v4.new_code_cell(
        "score_df = master_df[['amfi_code', 'scheme_name', 'expense_ratio_pct']].copy()\n"
        "score_df = score_df.merge(cagr_df, on='amfi_code')\n"
        "score_df = score_df.merge(ratios_df, on='amfi_code')\n"
        "score_df = score_df.merge(alpha_beta_df, on='amfi_code')\n"
        "score_df = score_df.merge(drawdown_df, on='amfi_code')\n\n"
        "score_df['rank_3yr'] = score_df['cagr_3yr_pct'].rank(pct=True) * 100\n"
        "score_df['rank_Sharpe'] = score_df['sharpe_ratio'].rank(pct=True) * 100\n"
        "score_df['rank_Alpha'] = score_df['alpha'].rank(pct=True) * 100\n"
        "score_df['rank_expense'] = score_df['expense_ratio_pct'].rank(ascending=False, pct=True) * 100\n"
        "score_df['rank_max_dd'] = score_df['max_drawdown_pct'].rank(ascending=True, pct=True) * 100\n\n"
        "score_df['score'] = (\n"
        "    0.30 * score_df['rank_3yr'] +\n"
        "    0.25 * score_df['rank_Sharpe'] +\n"
        "    0.20 * score_df['rank_Alpha'] +\n"
        "    0.15 * score_df['rank_expense'] +\n"
        "    0.10 * score_df['rank_max_dd']\n"
        ")\n"
        "score_df['scorecard_rank'] = score_df['score'].rank(ascending=False, method='min').astype(int)\n"
        "score_df = score_df.sort_values('scorecard_rank')\n\n"
        "print(\"Top 5 Funds according to Scorecard:\")\n"
        "score_df[['scorecard_rank', 'scheme_name', 'score', 'cagr_3yr_pct', 'sharpe_ratio', 'alpha']].head(5)"
    ),
    nbf.v4.new_markdown_cell(
        "## 7. Benchmark Comparison Line Chart\n\n"
        "Plot the top 5 funds normalized NAV vs Nifty 50 and Nifty 100 indices (starting at 100 on 2023-05-29)."
    ),
    nbf.v4.new_code_cell(
        "top_5 = score_df.head(5)\n"
        "top_5_codes = top_5['amfi_code'].tolist()\n"
        "top_5_names = top_5['scheme_name'].tolist()\n\n"
        "start_date = pd.Timestamp(\"2023-05-29\")\n"
        "end_date = pd.Timestamp(\"2026-05-29\")\n\n"
        "nifty50_all = bench_df[(bench_df['index_name'] == 'NIFTY50') & (bench_df['date'] >= start_date) & (bench_df['date'] <= end_date)].sort_values('date')\n"
        "nifty100_all = bench_df[(bench_df['index_name'] == 'NIFTY100') & (bench_df['date'] >= start_date) & (bench_df['date'] <= end_date)].sort_values('date')\n\n"
        "plt.figure(figsize=(12, 7))\n"
        "sns.set_theme(style=\"whitegrid\")\n\n"
        "for code, name in zip(top_5_codes, top_5_names):\n"
        "    fund_data = nav_df[(nav_df['amfi_code'] == code) & (nav_df['date'] >= start_date) & (nav_df['date'] <= end_date)].sort_values('date')\n"
        "    base_nav = fund_data.iloc[0]['nav']\n"
        "    normalized_nav = (fund_data['nav'] / base_nav) * 100\n"
        "    \n"
        "    plt.plot(fund_data['date'], normalized_nav, label=name.split(\" - \")[0], linewidth=1.5)\n"
        "    \n"
        "    fund_ret = fund_data['daily_return'].values[1:]\n"
        "    n50_ret = nifty50_all['daily_return'].values[1:]\n"
        "    n100_ret = nifty100_all['daily_return'].values[1:]\n"
        "    \n"
        "    min_len_50 = min(len(fund_ret), len(n50_ret))\n"
        "    min_len_100 = min(len(fund_ret), len(n100_ret))\n"
        "    \n"
        "    te_n50 = np.std(fund_ret[:min_len_50] - n50_ret[:min_len_50], ddof=1) * np.sqrt(252) * 100\n"
        "    te_n100 = np.std(fund_ret[:min_len_100] - n100_ret[:min_len_100], ddof=1) * np.sqrt(252) * 100\n"
        "    \n"
        "    print(f\"{name.split(' - ')[0]}:\")\n"
        "    print(f\"  TE vs Nifty 50: {te_n50:.4f}%\")\n"
        "    print(f\"  TE vs Nifty 100: {te_n100:.4f}%\")\n\n"
        "n50_base = nifty50_all.iloc[0]['close_value']\n"
        "normalized_n50 = (nifty50_all['close_value'] / n50_base) * 100\n"
        "plt.plot(nifty50_all['date'], normalized_n50, label='Nifty 50', color='black', linestyle='--', linewidth=2)\n\n"
        "n100_base = nifty100_all.iloc[0]['close_value']\n"
        "normalized_n100 = (nifty100_all['close_value'] / n100_base) * 100\n"
        "plt.plot(nifty100_all['date'], normalized_n100, label='Nifty 100', color='dimgray', linestyle=':', linewidth=2)\n\n"
        "plt.title(\"Top 5 Funds vs Benchmarks - 3 Year Normalized Performance (2023-05-29 = 100)\", fontsize=14, fontweight='bold', pad=15)\n"
        "plt.xlabel(\"Date\", fontsize=12, labelpad=10)\n"
        "plt.ylabel(\"Normalized NAV / Close Price\", fontsize=12, labelpad=10)\n"
        "plt.legend(loc='upper left', fontsize=10, frameon=True, shadow=True)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )
]

nb['cells'] = cells

with open(notebook_path, 'w', encoding='utf-8') as f:
    nbf.write(nb, f)

print(f"Generated notebook at {notebook_path}")
